import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Globe, MapPin, Sparkles } from 'lucide-react';
const Footer = () => {
    const currentYear = new Date().getFullYear();
    return (_jsxs("footer", { className: "bg-gray-900 text-gray-300", children: [_jsx("div", { className: "bg-gradient-to-r from-emerald-600 to-teal-700 py-16", children: _jsxs("div", { className: "container mx-auto px-6 text-center", children: [_jsxs("div", { className: "flex items-center justify-center gap-2 mb-4", children: [_jsx(Sparkles, { className: "w-5 h-5 text-amber-300" }), _jsx("span", { className: "text-emerald-100 text-sm font-medium", children: "\u5F00\u542F\u60A8\u7684\u5168\u7403\u4E4B\u65C5" })] }), _jsx("h3", { className: "text-3xl md:text-4xl font-bold text-white mb-6", style: { fontFamily: 'Noto Serif SC, serif' }, children: "\u51C6\u5907\u597D\u62D3\u5C55\u4E2D\u56FD\u5E02\u573A\u4E86\u5417\uFF1F" }), _jsx("p", { className: "text-emerald-100 text-lg max-w-2xl mx-auto mb-8", children: "\u4E13\u4E1A\u7684\u56E2\u961F\u3001\u4E30\u5BCC\u7684\u7ECF\u9A8C\uFF0C\u5E2E\u52A9\u60A8\u7684\u4EA7\u54C1\u5FEB\u901F\u8FDB\u5165\u4E2D\u56FD\u5E02\u573A" }), _jsx("a", { href: "#contact", className: "inline-flex items-center gap-2 bg-white text-emerald-700 px-8 py-4 rounded-full font-bold text-lg hover:shadow-xl transition-all hover:scale-105", children: "\u7ACB\u5373\u54A8\u8BE2" })] }) }), _jsxs("div", { className: "container mx-auto px-6 py-16", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10", children: [_jsxs("div", { className: "lg:col-span-1", children: [_jsxs("div", { className: "flex items-center gap-3 mb-6", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center", children: _jsx(Globe, { className: "w-7 h-7 text-white" }) }), _jsxs("div", { children: [_jsx("span", { className: "text-xl font-bold text-white", children: "\u4E0A\u6D77\u5F20\u5C0F\u5F3A" }), _jsx("span", { className: "block text-xs text-gray-400", children: "\u4F01\u4E1A\u54A8\u8BE2\u4E8B\u52A1\u6240" })] })] }), _jsx("p", { className: "text-gray-400 text-sm leading-relaxed mb-6", children: "\u4E13\u4E1A\u7684\u6D77\u5916\u4EA7\u54C1\u8FDB\u53E3\u54A8\u8BE2\u670D\u52A1\uFF0C\u5E2E\u52A9\u6D77\u5916\u4F01\u4E1A\u5FEB\u901F\u8FDB\u5165\u4E2D\u56FD\u5E02\u573A\u3002AI\u6280\u672F\u8D4B\u80FD\u4F01\u4E1A\u5168\u7403\u6269\u5F20\u3002" }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(MapPin, { className: "w-4 h-4" }), _jsx("span", { children: "\u4E0A\u6D77\u5E02" })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-white font-bold mb-6 text-lg", children: "\u6838\u5FC3\u670D\u52A1" }), _jsx("ul", { className: "space-y-3", children: [
                                            '海外选品服务',
                                            '采购代理服务',
                                            '市场准入咨询',
                                            '渠道对接服务',
                                            '品牌本地化',
                                            '海外市场调研',
                                        ].map((item, index) => (_jsx("li", { children: _jsx("a", { href: "#services", className: "text-gray-400 hover:text-emerald-400 transition-colors text-sm", children: item }) }, index))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-white font-bold mb-6 text-lg", children: "\u5168\u7403\u5E02\u573A" }), _jsx("ul", { className: "space-y-3", children: [
                                            { name: '日本', flag: '🇯🇵' },
                                            { name: '欧洲', flag: '🇪🇺' },
                                            { name: '东南亚', flag: '🌏' },
                                            { name: '澳大利亚', flag: '🦘' },
                                            { name: '美国', flag: '🇺🇸' },
                                            { name: '中东', flag: '🏜️' },
                                        ].map((item, index) => (_jsx("li", { children: _jsxs("a", { href: "#markets", className: "text-gray-400 hover:text-emerald-400 transition-colors text-sm flex items-center gap-2", children: [_jsx("span", { children: item.flag }), _jsx("span", { children: item.name })] }) }, index))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-white font-bold mb-6 text-lg", children: "\u5FEB\u901F\u94FE\u63A5" }), _jsx("ul", { className: "space-y-3", children: [
                                            { name: '关于我们', href: '#about' },
                                            { name: '服务项目', href: '#services' },
                                            { name: '全球市场', href: '#markets' },
                                            { name: 'AI工具', href: '#tools' },
                                            { name: '联系我们', href: '#contact' },
                                        ].map((item, index) => (_jsx("li", { children: _jsx("a", { href: item.href, className: "text-gray-400 hover:text-emerald-400 transition-colors text-sm", children: item.name }) }, index))) })] })] }), _jsx("div", { className: "mt-12 pt-8 border-t border-gray-800", children: _jsxs("div", { className: "flex flex-col md:flex-row justify-between items-center gap-4", children: [_jsxs("p", { className: "text-gray-500 text-sm", children: ["\u00A9 ", currentYear, " \u4E0A\u6D77\u5F20\u5C0F\u5F3A\u4F01\u4E1A\u54A8\u8BE2\u4E8B\u52A1\u6240. \u7248\u6743\u6240\u6709"] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsx("a", { href: "#", className: "text-gray-500 hover:text-emerald-400 text-sm transition-colors", children: "\u9690\u79C1\u653F\u7B56" }), _jsx("a", { href: "#", className: "text-gray-500 hover:text-emerald-400 text-sm transition-colors", children: "\u670D\u52A1\u6761\u6B3E" })] })] }) })] })] }));
};
export default Footer;
